export const shippingLineLogos = [
  { name: "Maersk", logo: "/company-logos/maersk.png", hasLogo: true },
  { name: "CMA CGM", logo: "/company-logos/cma-cgm.svg", hasLogo: true },
  { name: "MSC", logo: "/company-logos/msc.jpeg", hasLogo: true, width: 400, height: 400 },
  { name: "Hapag-Lloyd", logo: "/company-logos/hapag-lloyd.svg", hasLogo: true },
  { name: "ONE", logo: "/company-logos/one.svg", hasLogo: true },
  { name: "COSCO Shipping", logo: "/company-logos/cosco.png", hasLogo: true, width: 280, height: 180 },
  { name: "OOCL", logo: "/company-logos/oocl.svg", hasLogo: true },
  { name: "Unifeeder", logo: "/company-logos/unifeeder.png", hasLogo: true, width: 429, height: 127 },
  { name: "HMM", logo: "/company-logos/hmm.svg", hasLogo: true },
  { name: "PIL", logo: "/company-logos/pil.svg", hasLogo: true },
  { name: "Yang Ming", logo: "/company-logos/yang-ming.png", hasLogo: true },
  { name: "Sidra Line", logo: "/company-logos/sidraline.png", hasLogo: true },
  { name: "Arkas", logo: "/company-logos/arkas.png", hasLogo: true, width: 512, height: 157 },
  { name: "MPG", logo: "/company-logos/mpg.png", hasLogo: true, width: 851, height: 491 },
];

export const clientLogos = [
  { name: "BMW", logo: "/company-logos/BMW_idc2AOVkmA_0.jpeg", hasLogo: true, width: 480, height: 480 },
  { name: "Nissan", logo: "/company-logos/Nissan/Nissan_Logo_1.png", hasLogo: true, width: 800, height: 251 },
  { name: "BYD", logo: "/company-logos/BYD_idVcUXbGUk_1.png", hasLogo: true, width: 800, height: 154 },
  { name: "Itochu", logo: "/company-logos/Itochu_id-ed7QpMo_1.png", hasLogo: true, width: 800, height: 331 },
  { name: "Suzuki", logo: "/company-logos/suzuki.svg", hasLogo: true },
  { name: "Geely", logo: "/company-logos/geely.svg", hasLogo: true },
  { name: "Otsuka", logo: "/company-logos/otsuka.svg", hasLogo: true },
  { name: "Abou Ghaly Motors", logo: "/company-logos/Abou_Ghaly_Motors_id_I5ged4I_0.jpeg", hasLogo: true, width: 459, height: 459 },
  { name: "Mansour Group", logo: "/company-logos/mansour.png", hasLogo: true, width: 219, height: 230 },
  { name: "Mobica", logo: "/company-logos/mobica.jpg", hasLogo: true, width: 817, height: 817 },
  { name: "COFICAB", logo: "/company-logos/COFICAB.png", hasLogo: true, width: 193, height: 59 },
  { name: "KG Mobility", logo: "/company-logos/kg-mobility.png", hasLogo: true, width: 142, height: 44 },
  { name: "Jushi", logo: "/company-logos/jushi.png", hasLogo: true, width: 184, height: 37 },
];
